---
- name: Set up configuration parameters 1/2
  set_fact: mongodb_major_minor_version=v{{mongodb_version[:3]}} # the 'v' is necessary due to Ansible's number autoconversion quirks

- name: Set up configuration parameters 2/2
  set_fact:
    mongodb_daemon_name: "{{mongodb_config['daemon']}}"


- include: configure.yml
  when: mongodb_install
